### ISSUE TITLE
.DS_Store breaks plugin

### ISSUE THREAD

**Issue by dangodev** [DanielNetzer/docz-plugin-stencil#2]
**Describe the bug**
Followed the instruction steps and got this error:

```
> wait-on http://localhost:3333/ && docz dev

✖  fatal     Failed to build your files
✖  error     Error: ENOTDIR: not a directory, scandir 'src/components/.DS_Store'
```

**Reproducing this error**
```
touch src/components/.DS_Store
```

**Desktop (please complete the following information):**
- macOS Mojave

**Additional context**
It seems like the directory check is erring when it hits a hidden system file like `.DS_Store`. Manually removing the file works, but my system will just replace it again when it re-indexes that folder.

**Comment by DanielNetzer** [comment]
fixed in version docz-plugin-stencil@0.4.6
