### ISSUE TITLE
Is  docz/my-component.mdx autogenerated by this plugin?

### ISSUE THREAD

**Issue by kirankalyan5** [DanielNetzer/docz-plugin-stencil#4]
Hi, Thanks for this plugin, From the example I wanted to understand whether the docs/ my-component.mdx is auto-generated based on the my-component.readme.md?

if yes, is there any config which I have to add to enable the auto-generated.

Currently, I do see any MDX file generated in running the build.

**Comment by DanielNetzer** [comment]
Hello  @kirankalyan5, if you followed the installation of the plugin then it will scan your entire `components` folder and for each component will auto generate MDX file in the `docz` components folder.

**Comment by kirankalyan5** [comment]
Hi, @DanielNetzer thanks for the clarification.

changing `doczrc.ts` --> `doczrc.js` sloved the problem.
